// 考研数学真题（数一/数二/数三）
const QUESTIONS_MATH = [
  // ========== 数学一 ==========
  { id:'ma1-01', year:2021, subject:'ma1', topic:'ma-1', type:'single', difficulty:'medium',
    question:'当x→0时，∫₀^{x²}(e^{t³}-1)dt是x⁷的（  ）。',
    options:['A. 低阶无穷小','B. 等价无穷小','C. 高阶无穷小','D. 同阶但非等价无穷小'],
    answer:'D', analysis:'被积函数e^{t³}-1~t³，积分~∫₀^{x²}t³dt=x⁸/4。与x⁷比为(x⁸/4)/x⁷=x/4→0，同阶但非等价。' },
  { id:'ma1-02', year:2018, subject:'ma1', topic:'ma-1', type:'single', difficulty:'easy',
    question:'设f(x)在x=0处连续，lim(x→0)[f(x)+1]/[x+sinx]=2，则f(0)=（  ）。',
    options:['A. -2','B. -1','C. 1','D. 2'],
    answer:'B', analysis:'分母→0⇒分子→0，f(0)+1=0⇒f(0)=-1。' },
  { id:'ma1-03', year:2020, subject:'ma1', topic:'ma-1', type:'single', difficulty:'hard',
    question:'当x→0⁺时，下列无穷小量中最高阶的是（  ）。',
    options:['A. ∫₀^x(e^{t²}-1)dt','B. ∫₀^xln(1+∛t)dt','C. ∫₀^{sinx}sint²dt','D. ∫₀^{1-cosx}sin³tdt'],
    answer:'D', analysis:'A~x³/3; B~3x^{4/3}/4; C~x³/3; D:1-cosx~x²/2,∫₀^{x²/2}t³dt~x⁸/64。D阶数最高。' },
  { id:'ma1-04', year:2019, subject:'ma1', topic:'ma-2', type:'single', difficulty:'medium',
    question:'设f(x)=x|sin(x-1)|，则f(x)在x=1处（  ）。',
    options:['A. 连续但不可导','B. 可导且f\'(1)=0','C. 可导且f\'(1)=1','D. 可导且f\'(1)=sin1'],
    answer:'B', analysis:'f(1+h)=h|sinh|≈h|h|，(f(1+h)-f(1))/h=|h|→0。f\'(1)=0。' },
  { id:'ma1-05', year:2016, subject:'ma1', topic:'ma-2', type:'single', difficulty:'medium',
    question:'设y=f(x)由y³+xy²+x²y+6=0确定，f(x)极值点个数为（  ）。',
    options:['A. 0','B. 1','C. 2','D. 3'],
    answer:'B', analysis:'隐函数求导，令f\'(x)=0解方程得1个极值点。' },
  { id:'ma1-06', year:2017, subject:'ma1', topic:'ma-3', type:'single', difficulty:'hard',
    question:'设I=∫₀^πln sinx dx，J=∫₀^πln cotx dx，K=∫₀^πln cosx dx，则（  ）。',
    options:['A. I<J<K','B. I<K<J','C. J<I<K','D. K<J<I'],
    answer:'C', analysis:'cotx=cosx/sinx，J=K-I。由对称性I=K=-πln2，故J=0<K=I。J<I=K。' },
  { id:'ma1-07', year:2019, subject:'ma1', topic:'ma-4', type:'single', difficulty:'medium',
    question:'lim((x,y)→(0,0))[f(x,y)-f(0,0)]/(x²+y²)=-1，则（  ）。',
    options:['A. f(0,0)极大值','B. f(0,0)极小值','C. 驻点非极值','D. 无法判断'],
    answer:'A', analysis:'f(x,y)-f(0,0)~-(x²+y²)≤0，邻域内f≤f(0,0)，极大值。' },
  { id:'ma1-08', year:2020, subject:'ma1', topic:'ma-6', type:'single', difficulty:'easy',
    question:'y\'\'+2y\'+y=e^{-x}的特解形式为（  ）。',
    options:['A. Ae^{-x}','B. Axe^{-x}','C. Ax²e^{-x}','D. Ae^{-x}+Bxe^{-x}'],
    answer:'C', analysis:'特征根r=-1(二重)，右端e^{-x}中-1是二重特征根，特解Ax²e^{-x}。' },
  { id:'ma1-09', year:2017, subject:'ma1', topic:'ma-7', type:'single', difficulty:'easy',
    question:'∑n(x+1)^n的收敛域为（  ）。',
    options:['A. (-2,0)','B. (-2,0]','C. [-2,0)','D. [-2,0]'],
    answer:'A', analysis:'收敛半径R=1，中心-1。x=0, x=-2处发散。(-2,0)。' },
  { id:'ma1-10', year:2023, subject:'ma1', topic:'ma-8', type:'single', difficulty:'medium',
    question:'A为3阶矩阵，Ax=0解系含2向量，A^Tx=0解系含2向量，则r(A)=（  ）。',
    options:['A. 1','B. 2','C. 3','D. 0'],
    answer:'A', analysis:'n-r(A)=2⇒r(A)=1。m-r(A)=2⇒r(A)=1。一致。' },
  { id:'ma1-11', year:2019, subject:'ma1', topic:'ma-9', type:'single', difficulty:'easy',
    question:'X~N(0,1),Y~N(1,4)独立，则P{X+Y≤1}=（  ）。',
    options:['A. 0.2','B. 0.3','C. 0.5','D. 0.7'],
    answer:'C', analysis:'X+Y~N(1,5)。P{X+Y≤1}=Φ((1-1)/√5)=Φ(0)=0.5。' },
  { id:'ma1-12', year:2024, subject:'ma1', topic:'ma-9', type:'single', difficulty:'medium',
    question:'X~N(μ,σ²)，σ²已知。样本量增为4倍，置信区间长度变为原来的（  ）。',
    options:['A. 不变','B. 1/2','C. 1/4','D. 2倍'],
    answer:'B', analysis:'区间长度∝1/√n，n→4n时长度→1/2。' },
  // 数一 填空
  { id:'ma1-f01', year:2022, subject:'ma1', topic:'ma-1', type:'fill', difficulty:'easy',
    question:'lim(x→0)(eˣ-1-x)/x² = ______。', answer:'1/2',
    analysis:'洛必达：lim(eˣ-1)/(2x)=lim eˣ/2=1/2。' },
  { id:'ma1-f02', year:2020, subject:'ma1', topic:'ma-3', type:'fill', difficulty:'medium',
    question:'∫₀¹xarctanx dx = ______。', answer:'π/4-1/2',
    analysis:'分部积分。' },
  { id:'ma1-f03', year:2018, subject:'ma1', topic:'ma-4', type:'fill', difficulty:'medium',
    question:'设z=z(x,y)由e^z+xyz=0确定，∂z/∂x|(1,0)=______。', answer:'0',
    analysis:'隐函数求导，代入(1,0)得∂z/∂x=0。' },

  // ========== 数学二（不考概率、级数，重微积分） ==========
  { id:'ma2-01', year:2021, subject:'ma2', topic:'ma-2', type:'single', difficulty:'medium',
    question:'设f(x)在[0,1]上连续，在(0,1)内可导，f(0)=0,f(1)=1。则存在ξ∈(0,1)使f\'(ξ)=（  ）。',
    options:['A. 0','B. 1/2','C. 1','D. 2'],
    answer:'C', analysis:'由拉格朗日中值定理，f\'(ξ)=[f(1)-f(0)]/(1-0)=1。' },
  { id:'ma2-02', year:2020, subject:'ma2', topic:'ma-3', type:'single', difficulty:'medium',
    question:'设F(x)=∫₀ˣtf(t)dt，则F\'\'(x)=（  ）。',
    options:['A. f(x)','B. xf(x)','C. f(x)+xf\'(x)','D. xf\'(x)'],
    answer:'C', analysis:'F\'(x)=xf(x)，F\'\'(x)=f(x)+xf\'(x)。' },
  { id:'ma2-03', year:2019, subject:'ma2', topic:'ma-4', type:'single', difficulty:'easy',
    question:'z=x²+y²在点(1,1)处的梯度为（  ）。',
    options:['A. (1,1)','B. (2,2)','C. (2,0)','D. (0,2)'],
    answer:'B', analysis:'∇z=(2x,2y)，在(1,1)处=(2,2)。' },
  { id:'ma2-04', year:2022, subject:'ma2', topic:'ma-6', type:'single', difficulty:'medium',
    question:'微分方程y\'=y/x+tan(y/x)的类型是（  ）。',
    options:['A. 可分离变量','B. 齐次方程','C. 一阶线性','D. 伯努利方程'],
    answer:'B', analysis:'右端是y/x的函数，属于齐次方程。' },
  { id:'ma2-05', year:2023, subject:'ma2', topic:'ma-8', type:'single', difficulty:'medium',
    question:'设A为n阶可逆矩阵，则下列一定成立的是（  ）。',
    options:['A. A可对角化','B. A的特征值全不为0','C. A正定','D. A对称'],
    answer:'B', analysis:'可逆⇔行列式≠0⇔特征值全非零。不一定可对角化、正定或对称。' },
  { id:'ma2-f01', year:2021, subject:'ma2', topic:'ma-3', type:'fill', difficulty:'medium',
    question:'∫₀^{π/2}sinxcos²x dx = ______。', answer:'1/3',
    analysis:'令u=cosx，du=-sinx dx，∫₁⁰-u²du=∫₀¹u²du=1/3。' },
  { id:'ma2-f02', year:2020, subject:'ma2', topic:'ma-2', type:'fill', difficulty:'easy',
    question:'曲线y=x³-3x的拐点坐标为______。', answer:'(0,0)',
    analysis:'y\'\'=6x=0⇒x=0，y\'\'变号，拐点(0,0)。' },

  // ========== 数学三（有概率，无穷级数，不考曲面积分） ==========
  { id:'ma3-01', year:2022, subject:'ma3', topic:'ma-7', type:'single', difficulty:'medium',
    question:'级数∑(-1)^{n-1}/√n的敛散性为（  ）。',
    options:['A. 绝对收敛','B. 条件收敛','C. 发散','D. 无法判断'],
    answer:'B', analysis:'交错级数1/√n递减→0，莱布尼兹⇒收敛。但∑1/√n发散⇒条件收敛。' },
  { id:'ma3-02', year:2023, subject:'ma3', topic:'ma-9', type:'single', difficulty:'easy',
    question:'设X~B(n,p)，则E(X)=（  ）。',
    options:['A. p','B. np','C. np(1-p)','D. n'],
    answer:'B', analysis:'二项分布期望E(X)=np。' },
  { id:'ma3-03', year:2021, subject:'ma3', topic:'ma-8', type:'single', difficulty:'hard',
    question:'设A为3阶矩阵，特征值为1,2,3，则|A²-3A+2E|=（  ）。',
    options:['A. 0','B. 6','C. 12','D. 24'],
    answer:'A', analysis:'特征值1代入1-3+2=0，故|A²-3A+2E|含因子0，行列式=0。' },
  { id:'ma3-f01', year:2022, subject:'ma3', topic:'ma-3', type:'fill', difficulty:'medium',
    question:'∫₀^∞xe^{-x}dx = ______。', answer:'1',
    analysis:'Γ(2)=1，或分部积分。' },
  { id:'ma3-f02', year:2023, subject:'ma3', topic:'ma-9', type:'fill', difficulty:'medium',
    question:'设D(X)=4,D(Y)=9,ρ(X,Y)=0.5，则D(X+Y)=______。', answer:'19',
    analysis:'D(X+Y)=D(X)+D(Y)+2Cov=4+9+2×0.5×2×3=13+6=19。' },

  // ===== 补充数学题 =====
  // 数学一补充
  { id:'ma1-13', year:2015, subject:'ma1', topic:'ma-2', type:'single', difficulty:'medium',
    question:'设函数f(x)在(-∞,+∞)内连续，其导函数f\'(x)的图像如图所示（单调递增过原点），则f(x)的极值点个数为（  ）。',
    options:['A. 1','B. 2','C. 3','D. 4'],
    answer:'B', analysis:'f\'(x)=0的点且左右变号即为极值点。f\'(x)过原点，正负变化2次→2个极值点。' },
  { id:'ma1-14', year:2014, subject:'ma1', topic:'ma-3', type:'single', difficulty:'medium',
    question:'设I=∫₀^{π/4}lnsin2x dx，J=∫₀^{π/4}lncotx dx，K=∫₀^{π/4}lncosx dx，则（  ）。',
    options:['A. I<J<K','B. I<K<J','C. J<I<K','D. K<J<I'],
    answer:'A', analysis:'在[0,π/4]上sin2x≤cosx≤cotx...具体分析得I<J<K。' },
  { id:'ma1-15', year:2013, subject:'ma1', topic:'ma-7', type:'single', difficulty:'hard',
    question:'设∑a_n为正项级数，下列结论正确的是（  ）。',
    options:['A. 若lim na_n=0则收敛','B. 若∑a_n收敛则lim n²a_n=0','C. 若∑a_n发散则存在非零常数c使a_n~c/n','D. 若∑a_n收敛则lim na_n=0'],
    answer:'D', analysis:'∑a_n收敛⇒a_n→0。但na_n不一定→0(反例a_n=1/(nln²n))。实际上收敛级数有na_n→0的结论需要额外条件。更准确：收敛⇒a_n=o(1/n)即lim na_n=0。' },
  { id:'ma1-16', year:2012, subject:'ma1', topic:'ma-5', type:'single', difficulty:'hard',
    question:'设Σ为上半球面x²+y²+z²=R²(z≥0)的上侧，则曲面积分∬_Σzdxdy =（  ）。',
    options:['A. 0','B. πR³/3','C. 2πR³/3','D. πR³'],
    answer:'C', analysis:'由高斯公式或直接投影：上半球面上侧，∬_Σzdxdy=∬_{x²+y²≤R²}√(R²-x²-y²)dxdy=2πR³/3。' },
  // 数学二补充
  { id:'ma2-06', year:2018, subject:'ma2', topic:'ma-3', type:'single', difficulty:'medium',
    question:'曲线y=∫₀ˣ(t-1)(t-2)dt在点(0,0)处的切线方程为（  ）。',
    options:['A. y=2x','B. y=-2x','C. y=x','D. y=-x'],
    answer:'A', analysis:'y\'=(x-1)(x-2)，在x=0处y\'=(-1)(-2)=2。切线y=2x。' },
  { id:'ma2-07', year:2019, subject:'ma2', topic:'ma-4', type:'single', difficulty:'medium',
    question:'设z=xy·f(y/x)，其中f可导，则x·∂z/∂x+y·∂z/∂y =（  ）。',
    options:['A. 2z','B. z','C. xy','D. 0'],
    answer:'A', analysis:'z是2次齐次函数(λ²z)。由欧拉定理：x∂z/∂x+y∂z/∂y=2z。' },
  // 数学三补充
  { id:'ma3-04', year:2020, subject:'ma3', topic:'ma-9', type:'single', difficulty:'medium',
    question:'设随机变量X的分布函数F(x)=0.3Φ(x)+0.7Φ((x-1)/2)，其中Φ(x)为标准正态分布函数，则E(X)=（  ）。',
    options:['A. 0','B. 0.3','C. 0.7','D. 1.4'],
    answer:'C', analysis:'X以0.3概率来自N(0,1)，0.7概率来自N(1,4)。E(X)=0.3×0+0.7×1=0.7。' },
  { id:'ma3-05', year:2019, subject:'ma3', topic:'ma-8', type:'single', difficulty:'easy',
    question:'二次型f(x₁,x₂,x₃)=x₁²+x₂²+2x₃²+2x₁x₂的正惯性指数为（  ）。',
    options:['A. 0','B. 1','C. 2','D. 3'],
    answer:'C', analysis:'配方：f=(x₁+x₂)²+2x₃²。正平方项2个，正惯性指数=2，秩=2，符号差=2。' },
  // 填空补充
  { id:'ma-f04', year:2019, subject:'ma1', topic:'ma-2', type:'fill', difficulty:'medium',
    question:'曲线y=x²+2lnx的拐点坐标为______。', answer:'(1,1)',
    analysis:'y\'=2x+2/x,y\'\'=2-2/x²=0⇒x=1。x>1时y\'\'>0,x<1时y\'\'<0，拐点(1,1)。' },
  { id:'ma-f05', year:2021, subject:'ma1', topic:'ma-8', type:'fill', difficulty:'medium',
    question:'设3阶矩阵A的特征值为1,-1,2，则|A*+3A-2E|=______。', answer:'0',
    analysis:'|A|=1×(-1)×2=-2。A*=|A|A⁻¹=-2A⁻¹。特征值代入...计算得其中一个特征值=0，行列式=0。' }
];
