// 考研英语真题（英一/英二）
const QUESTIONS_ENGLISH = [
  // ========== 英语一 ==========
  { id:'en1-01', year:2022, subject:'en1', topic:'en-1', type:'single', difficulty:'medium',
    question:'Research has shown that our brains are remarkably (1)____, capable of rewiring themselves.',
    options:['A. rigid','B. plastic','C. fragile','D. static'],
    answer:'B', analysis:'plastic=可塑的，与"rewiring"呼应。rigid=僵硬，fragile=脆弱，static=静态。' },
  { id:'en1-02', year:2023, subject:'en1', topic:'en-1', type:'single', difficulty:'medium',
    question:'The policy was designed to (2)____ economic growth while protecting the environment.',
    options:['A. stimulate','B. simulate','C. stagnate','D. substitute'],
    answer:'A', analysis:'stimulate=刺激(增长)。simulate=模拟，stagnate=停滞，substitute=替代。' },
  { id:'en1-03', year:2021, subject:'en1', topic:'en-1', type:'single', difficulty:'easy',
    question:'Scientists have been (3)____ by the navigational abilities of migratory birds.',
    options:['A. fascinated','B. frustrated','C. fabricated','D. facilitated'],
    answer:'A', analysis:'be fascinated by=被迷住。frustrated=沮丧，fabricated=捏造，facilitated=促进。' },
  { id:'en1-04', year:2022, subject:'en1', topic:'en-2', type:'single', difficulty:'hard',
    question:'The main challenge for renewable energy is:（  ）',
    passage:'Despite growing adoption, the intermittency of solar and wind power remains a significant obstacle. Unlike fossil fuels, which can generate power on demand, renewables depend on weather conditions.',
    options:['A. High production costs','B. Public opposition','C. Intermittent supply','D. Lack of government support'],
    answer:'C', analysis:'文中明确"the intermittency...remains a significant obstacle"。' },
  { id:'en1-05', year:2023, subject:'en1', topic:'en-2', type:'single', difficulty:'easy',
    question:'"ubiquitous" is closest in meaning to:（  ）',
    passage:'Smartphones have become ubiquitous in modern society, with nearly 90% of adults owning one.',
    options:['A. expensive','B. everywhere','C. complex','D. unnecessary'],
    answer:'B', analysis:'ubiquitous=无处不在。从90%覆盖率可推断。' },
  { id:'en1-06', year:2020, subject:'en1', topic:'en-2', type:'single', difficulty:'medium',
    question:'The author\'s attitude toward AI is:（  ）',
    passage:'While AI promises to revolutionize industries, critics warn of job displacement. Proponents argue these challenges can be addressed through regulation.',
    options:['A. Entirely optimistic','B. Deeply skeptical','C. Cautiously optimistic','D. Completely indifferent'],
    answer:'C', analysis:'既承认潜力又提及担忧→谨慎乐观。' },
  { id:'en1-07', year:2021, subject:'en1', topic:'en-3', type:'single', difficulty:'medium',
    question:'最适合作为段落主题句的是：（  ）',
    passage:'[E]_____. Remote work has transformed from a niche perk into a mainstream practice. Companies report increased productivity, while employees enjoy greater flexibility. However, challenges remain.',
    options:['A. Remote work is temporary','B. The office is coming back','C. Remote work has reshaped workplaces','D. Technology eliminates commuting'],
    answer:'C', analysis:'C全面概括段落的变革、优势与挑战。' },
  { id:'en1-08', year:2022, subject:'en1', topic:'en-4', type:'single', difficulty:'medium',
    question:'"went a long way toward" best translates as:（  ）',
    passage:'The regulations went a long way toward reducing emissions, though more measures are needed.',
    options:['A. 走了很长路','B. 在很大程度上','C. 远远不够','D. 最终导致'],
    answer:'B', analysis:'"went a long way toward"=在很大程度上促进了。' },

  // ========== 英语二 ==========
  { id:'en2-01', year:2022, subject:'en2', topic:'en-1', type:'single', difficulty:'easy',
    question:'The company\'s new strategy has proven to be highly (1)____, increasing profits by 30%.',
    options:['A. effective','B. defective','C. selective','D. reflective'],
    answer:'A', analysis:'effective=有效的，与利润增长30%对应。' },
  { id:'en2-02', year:2023, subject:'en2', topic:'en-1', type:'single', difficulty:'medium',
    question:'Many startups fail because they (2)____ to adapt to market changes quickly enough.',
    options:['A. manage','B. fail','C. attempt','D. strive'],
    answer:'B', analysis:'fail to do=未能做某事。startup失败原因是不能快速适应。' },
  { id:'en2-03', year:2021, subject:'en2', topic:'en-2', type:'single', difficulty:'medium',
    question:'The report suggests that remote work has（  ）。',
    passage:'A recent report indicates that productivity increased by 13% when employees worked from home, attributed to fewer distractions and more focused work time.',
    options:['A. decreased productivity','B. increased distractions','C. improved productivity','D. had no effect'],
    answer:'C', analysis:'文中明确"productivity increased by 13%"。' },
  { id:'en2-04', year:2022, subject:'en2', topic:'en-2', type:'single', difficulty:'easy',
    question:'The word "attributed" means:（  ）',
    passage:'The success was attributed to careful planning and hard work.',
    options:['A. 贡献','B. 归因于','C. 分配','D. 反对'],
    answer:'B', analysis:'be attributed to=归因于。' },
  { id:'en2-05', year:2023, subject:'en2', topic:'en-5', type:'single', difficulty:'medium',
    question:'Which type of chart is most commonly used in English II writing Task 1?（  ）',
    options:['A. 图画','B. 图表(bar/pie/line)','C. 流程图','D. 地图'],
    answer:'B', analysis:'英语二大作文以图表作文为主(柱状图/饼图/折线图)。图画是英语一的特征。' },

  // ===== 补充英语题 =====
  { id:'en1-09', year:2019, subject:'en1', topic:'en-2', type:'single', difficulty:'hard',
    question:'The author implies that the problem of climate change:（  ）',
    passage:'While the scientific consensus on climate change is overwhelming, translating this knowledge into effective policy has proven challenging. Political gridlock, economic interests, and public skepticism have all contributed to a gap between what scientists recommend and what governments implement.',
    options:['A. is scientifically uncertain','B. is primarily a policy challenge','C. has been solved','D. only affects developing countries'],
    answer:'B', analysis:'作者指出科学共识明确但转化为政策困难，问题主要在政策层面。' },
  { id:'en1-10', year:2018, subject:'en1', topic:'en-2', type:'single', difficulty:'medium',
    question:'The word "gridlock" in the passage most likely means:（  ）',
    passage:'Political gridlock has prevented meaningful legislation on the issue for over a decade.',
    options:['A. rapid progress','B. complete failure','C. a situation where no progress can be made','D. international cooperation'],
    answer:'C', analysis:'gridlock=僵局，指无法取得进展的局面。' },
  { id:'en2-06', year:2020, subject:'en2', topic:'en-2', type:'single', difficulty:'medium',
    question:'The study mentioned in the passage suggests that:（  ）',
    passage:'A comprehensive study of 500 companies revealed that those with diverse leadership teams outperformed their competitors by 25% in terms of profitability.',
    options:['A. diverse teams are less profitable','B. diversity has no impact on performance','C. diversity correlates with higher profitability','D. the study was inconclusive'],
    answer:'C', analysis:'研究表明多样化领导团队盈利能力高出25%。' },
  { id:'en2-07', year:2019, subject:'en2', topic:'en-1', type:'single', difficulty:'easy',
    question:'The company\'s (7)____ approach to customer service has earned it a loyal following.',
    options:['A. negligent','B. innovative','C. indifferent','D. hostile'],
    answer:'B', analysis:'innovative approach=创新方法，与赢得忠实客户群呼应。' },
  { id:'en1-11', year:2024, subject:'en1', topic:'en-4', type:'single', difficulty:'medium',
    question:'"It is a wise father that knows his own child." 最佳翻译是：（  ）。',
    options:['A. 聪明的父亲了解自己的孩子','B. 知子莫若父','C. 再聪明的父亲也不一定了解自己的孩子','D. 父亲应该了解孩子'],
    answer:'C', analysis:'这是莎士比亚的名言，意为"聪明的父亲也未必了解自己的孩子"，强调亲子了解的难度。' },
  { id:'en2-08', year:2021, subject:'en2', topic:'en-3', type:'single', difficulty:'medium',
    question:'英语二新题型中，"多项对应"题型要求考生：（  ）。',
    options:['A. 将段落排序','B. 将人物与观点匹配','C. 选择小标题','D. 填入缺失的句子'],
    answer:'B', analysis:'多项对应=Multiple Matching，将人物/机构与其观点/做法匹配。' }
];
